// Generated by gencpp from file imu/CarPose.msg
// DO NOT EDIT!


#ifndef IMU_MESSAGE_CARPOSE_H
#define IMU_MESSAGE_CARPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace imu
{
template <class ContainerAllocator>
struct CarPose_
{
  typedef CarPose_<ContainerAllocator> Type;

  CarPose_()
    : header()
    , roll(0.0)
    , roll_relative(0.0)
    , pitch(0.0)
    , pitch_relative(0.0)
    , yaw(0.0)
    , yaw_relative(0.0)  {
    }
  CarPose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , roll(0.0)
    , roll_relative(0.0)
    , pitch(0.0)
    , pitch_relative(0.0)
    , yaw(0.0)
    , yaw_relative(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _roll_relative_type;
  _roll_relative_type roll_relative;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _pitch_relative_type;
  _pitch_relative_type pitch_relative;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _yaw_relative_type;
  _yaw_relative_type yaw_relative;




  typedef boost::shared_ptr< ::imu::CarPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu::CarPose_<ContainerAllocator> const> ConstPtr;

}; // struct CarPose_

typedef ::imu::CarPose_<std::allocator<void> > CarPose;

typedef boost::shared_ptr< ::imu::CarPose > CarPosePtr;
typedef boost::shared_ptr< ::imu::CarPose const> CarPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu::CarPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu::CarPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'imu': ['/root/workspace/betagun/src/imu/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu::CarPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu::CarPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu::CarPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu::CarPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu::CarPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu::CarPose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu::CarPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "765b9e32d0441b8f51f41e5ac9438bb0";
  }

  static const char* value(const ::imu::CarPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x765b9e32d0441b8fULL;
  static const uint64_t static_value2 = 0x51f41e5ac9438bb0ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu::CarPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu/CarPose";
  }

  static const char* value(const ::imu::CarPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu::CarPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float32 roll\n\
float32 roll_relative\n\
float32 pitch\n\
float32 pitch_relative\n\
float32 yaw\n\
float32 yaw_relative\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::imu::CarPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu::CarPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.roll);
      stream.next(m.roll_relative);
      stream.next(m.pitch);
      stream.next(m.pitch_relative);
      stream.next(m.yaw);
      stream.next(m.yaw_relative);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu::CarPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu::CarPose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "roll_relative: ";
    Printer<float>::stream(s, indent + "  ", v.roll_relative);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "pitch_relative: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_relative);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "yaw_relative: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_relative);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_MESSAGE_CARPOSE_H
