// Generated by gencpp from file wheel_odom/CarSpeed.msg
// DO NOT EDIT!


#ifndef WHEEL_ODOM_MESSAGE_CARSPEED_H
#define WHEEL_ODOM_MESSAGE_CARSPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheel_odom
{
template <class ContainerAllocator>
struct CarSpeed_
{
  typedef CarSpeed_<ContainerAllocator> Type;

  CarSpeed_()
    : left_speed(0.0)
    , right_speed(0.0)
    , vx(0.0)
    , vy(0.0)
    , vth(0.0)  {
    }
  CarSpeed_(const ContainerAllocator& _alloc)
    : left_speed(0.0)
    , right_speed(0.0)
    , vx(0.0)
    , vy(0.0)
    , vth(0.0)  {
  (void)_alloc;
    }



   typedef float _left_speed_type;
  _left_speed_type left_speed;

   typedef float _right_speed_type;
  _right_speed_type right_speed;

   typedef float _vx_type;
  _vx_type vx;

   typedef float _vy_type;
  _vy_type vy;

   typedef float _vth_type;
  _vth_type vth;




  typedef boost::shared_ptr< ::wheel_odom::CarSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheel_odom::CarSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct CarSpeed_

typedef ::wheel_odom::CarSpeed_<std::allocator<void> > CarSpeed;

typedef boost::shared_ptr< ::wheel_odom::CarSpeed > CarSpeedPtr;
typedef boost::shared_ptr< ::wheel_odom::CarSpeed const> CarSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheel_odom::CarSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheel_odom::CarSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheel_odom

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'wheel_odom': ['/root/workspace/betagun/src/wheel_odom/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheel_odom::CarSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheel_odom::CarSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheel_odom::CarSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheel_odom::CarSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheel_odom::CarSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheel_odom::CarSpeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheel_odom::CarSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "262aadc0a5d48657eda9fd254eaeedbe";
  }

  static const char* value(const ::wheel_odom::CarSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x262aadc0a5d48657ULL;
  static const uint64_t static_value2 = 0xeda9fd254eaeedbeULL;
};

template<class ContainerAllocator>
struct DataType< ::wheel_odom::CarSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheel_odom/CarSpeed";
  }

  static const char* value(const ::wheel_odom::CarSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheel_odom::CarSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left_speed\n\
float32 right_speed\n\
float32 vx\n\
float32 vy\n\
float32 vth\n\
";
  }

  static const char* value(const ::wheel_odom::CarSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheel_odom::CarSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_speed);
      stream.next(m.right_speed);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheel_odom::CarSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheel_odom::CarSpeed_<ContainerAllocator>& v)
  {
    s << indent << "left_speed: ";
    Printer<float>::stream(s, indent + "  ", v.left_speed);
    s << indent << "right_speed: ";
    Printer<float>::stream(s, indent + "  ", v.right_speed);
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
    s << indent << "vth: ";
    Printer<float>::stream(s, indent + "  ", v.vth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEEL_ODOM_MESSAGE_CARSPEED_H
